[CmdletBinding()]
param(
    [string]$InstallDir = $(if ($env:TIZ_INSTALL_DIR) { $env:TIZ_INSTALL_DIR } else { "~\tiz-downloader" }),
    [string]$OutputDir = $(if ($env:TIZ_OUTPUT_DIR) { $env:TIZ_OUTPUT_DIR } else { "~\files\sports\Cycling" }),
    [string]$TaskName = "tiz_cycling_downloader",
    [string]$TaskTime = "06:00",
    [switch]$SkipScheduledTask
)

$ErrorActionPreference = "Stop"

function Resolve-UserPath {
    param([string]$PathValue)
    return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($PathValue)
}

function Get-PythonLauncher {
    if (Get-Command py -ErrorAction SilentlyContinue) {
        return @("py", "-3")
    }
    if (Get-Command python -ErrorAction SilentlyContinue) {
        return @("python")
    }
    throw "Python 3 was not found in PATH. Install Python 3.8+ first."
}

function Install-LocalDeno {
    if (Test-Path $script:DenoBin) {
        Write-Host "Local Deno already installed: $script:DenoBin"
        return
    }

    Write-Host "Installing local Deno runtime..."
    New-Item -ItemType Directory -Force -Path $script:DenoDir | Out-Null

    $env:DENO_INSTALL = $script:DenoDir
    try {
        Invoke-RestMethod "https://deno.land/install.ps1" | Invoke-Expression
    }
    finally {
        Remove-Item Env:DENO_INSTALL -ErrorAction SilentlyContinue
    }

    if (-not (Test-Path $script:DenoBin)) {
        throw "Deno install did not produce $script:DenoBin"
    }
}

function Write-EnvFile {
    $denoBinDir = Join-Path $script:DenoDir "bin"
    $contents = @"
# Generated by setup.ps1 for tiz-cycling-downloader.

`$env:PATH = "$denoBinDir;`$env:PATH"
`$env:TIZ_OUTPUT_DIR = "$script:OutputDirResolved"
`$env:TIZ_YTDLP_JS_RUNTIMES = "deno:$script:DenoBin"

# Place an exported Netscape-format cookie file at:
#   $script:CookieFile
# The downloader auto-detects it there, so no extra env var is required.

# Uncomment this only if yt-dlp needs to fetch EJS scripts remotely:
# `$env:TIZ_YTDLP_REMOTE_COMPONENTS = "ejs:github"
"@

    Set-Content -Path $script:EnvFile -Value $contents -Encoding UTF8
}

function Write-RunnerScript {
    $contents = @"
param(
    [switch]`$DryRun,
    [int]`$Since = 1,
    [string]`$Url = "",
    [string]`$Output = ""
)

. "`$PSScriptRoot\tiz-env.ps1"

`$python = Join-Path `$PSScriptRoot "venv\Scripts\python.exe"
`$script = Join-Path `$PSScriptRoot "tiz_cycling_downloader.py"
`$args = @(`$script)

if (`$Since -gt 0) {
    `$args += @("--since", "`$Since")
}
if (`$DryRun) {
    `$args += "--dry-run"
}
if (`$Url) {
    `$args += @("--url", `$Url)
}
if (`$Output) {
    `$args += @("--output", `$Output)
}

& `$python @args
exit `$LASTEXITCODE
"@

    Set-Content -Path $script:RunnerFile -Value $contents -Encoding UTF8
}

function Register-DownloaderTask {
    if ($SkipScheduledTask) {
        Write-Host "Skipping scheduled task creation."
        return
    }

    if (-not (Get-Command Register-ScheduledTask -ErrorAction SilentlyContinue)) {
        Write-Warning "ScheduledTasks module not available. Skipping scheduled task creation."
        return
    }

    $taskRun = [DateTime]::ParseExact($TaskTime, "HH:mm", $null)
    $actionArgs = "-NoProfile -ExecutionPolicy Bypass -Command ""& { & '$script:RunnerFile' -Since 1 *>> '$script:LogFile' }"""
    $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $actionArgs
    $trigger = New-ScheduledTaskTrigger -Daily -At $taskRun
    $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
    $principal = New-ScheduledTaskPrincipal -UserId ([Security.Principal.WindowsIdentity]::GetCurrent().Name) -LogonType InteractiveToken -RunLevel Limited

    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null
    Write-Host "Scheduled task updated: $TaskName ($TaskTime daily, runs while this user is logged in)"
}

$InstallDirResolved = Resolve-UserPath $InstallDir
$OutputDirResolved = Resolve-UserPath $OutputDir
$VenvDir = Join-Path $InstallDirResolved "venv"
$PythonExe = Join-Path $VenvDir "Scripts\python.exe"
$PipExe = Join-Path $VenvDir "Scripts\pip.exe"
$DenoDir = Join-Path $InstallDirResolved "deno"
$DenoBin = Join-Path $DenoDir "bin\deno.exe"
$EnvFile = Join-Path $InstallDirResolved "tiz-env.ps1"
$RunnerFile = Join-Path $InstallDirResolved "run-tiz.ps1"
$CookieFile = Join-Path $InstallDirResolved "youtube-cookies.txt"
$LogFile = Resolve-UserPath "~\tiz_downloader.log"

Write-Host "=== Tiz-Cycling Downloader Setup (Windows) ==="
Write-Host ""

Write-Host "Creating directories..."
New-Item -ItemType Directory -Force -Path $InstallDirResolved | Out-Null
New-Item -ItemType Directory -Force -Path $OutputDirResolved | Out-Null

Write-Host "Installing project files..."
Copy-Item -LiteralPath "tiz_cycling_downloader.py" -Destination $InstallDirResolved -Force
Copy-Item -LiteralPath "README.md" -Destination $InstallDirResolved -Force
Copy-Item -LiteralPath "AGENTS.md" -Destination $InstallDirResolved -Force
Copy-Item -LiteralPath "setup.sh" -Destination $InstallDirResolved -Force
Copy-Item -LiteralPath $PSCommandPath -Destination (Join-Path $InstallDirResolved "setup.ps1") -Force

$pythonLauncher = Get-PythonLauncher
$venvArgs = @()
if ($pythonLauncher.Count -gt 1) {
    $venvArgs += $pythonLauncher[1..($pythonLauncher.Count - 1)]
}
$venvArgs += @("-m", "venv", $VenvDir)

Write-Host "Creating Python venv..."
& $pythonLauncher[0] @venvArgs

Write-Host "Installing Python dependencies..."
& $PipExe install --quiet --upgrade pip
& $PipExe install --quiet "yt-dlp[default]" requests beautifulsoup4 lxml
Write-Host "Installed: yt-dlp[default], requests, beautifulsoup4, lxml"

Install-LocalDeno
Write-EnvFile
Write-RunnerScript
Register-DownloaderTask

if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
    Write-Host "Found ffmpeg: $((Get-Command ffmpeg).Source)"
}
else {
    Write-Warning "ffmpeg not found in PATH. Some YouTube formats may be limited until ffmpeg is installed."
}

Write-Host ""
Write-Host "=== Setup Complete ==="
Write-Host ""
Write-Host "  Install dir:    $InstallDirResolved"
Write-Host "  Output dir:     $OutputDirResolved"
Write-Host "  Local Deno:     $DenoBin"
Write-Host "  Env file:       $EnvFile"
Write-Host "  Runner file:    $RunnerFile"
Write-Host "  Cookie path:    $CookieFile"
Write-Host "  Log file:       $LogFile"
Write-Host ""
Write-Host "Usage:"
Write-Host "  Load env:       . .\tiz-env.ps1"
Write-Host "  Dry run:        .\run-tiz.ps1 -DryRun -Since 1"
Write-Host "  Run now:        .\run-tiz.ps1 -Since 1"
Write-Host "  Single URL:     .\run-tiz.ps1 -Url 'https://tiz-cycling.tv/video/...'"
Write-Host "  Add cookies:    copy youtube-cookies.txt to $CookieFile"
Write-Host "  Task check:     Get-ScheduledTask -TaskName $TaskName"
Write-Host ""
Write-Host "Override defaults with parameters:"
Write-Host "  .\setup.ps1 -OutputDir `"$HOME\files\sports\Cycling`""
