#!/bin/bash
# Setup script for tiz-cycling-downloader on a seedbox or Linux server
# Usage: bash setup.sh

set -euo pipefail

INSTALL_DIR="${TIZ_INSTALL_DIR:-$HOME/tiz-downloader}"
OUTPUT_DIR="${TIZ_OUTPUT_DIR:-$HOME/files/sports/Cycling}"
VENV_DIR="$INSTALL_DIR/venv"
DENO_DIR="$INSTALL_DIR/deno"
DENO_BIN="$DENO_DIR/bin/deno"
ENV_FILE="$INSTALL_DIR/tiz-env.sh"
COOKIE_FILE="$INSTALL_DIR/youtube-cookies.txt"

install_deno() {
    if [ -x "$DENO_BIN" ]; then
        echo "Local Deno already installed: $DENO_BIN"
        return
    fi

    echo "Installing local Deno runtime..."
    mkdir -p "$DENO_DIR"

    if command -v curl >/dev/null 2>&1; then
        curl -fsSL https://deno.land/install.sh | DENO_INSTALL="$DENO_DIR" sh
    elif command -v wget >/dev/null 2>&1; then
        wget -qO- https://deno.land/install.sh | DENO_INSTALL="$DENO_DIR" sh
    else
        echo "ERROR: curl or wget is required to install Deno." >&2
        exit 1
    fi
}

write_env_file() {
    cat > "$ENV_FILE" <<EOF
#!/bin/bash
# Generated by setup.sh for tiz-cycling-downloader.

export PATH="$DENO_DIR/bin:\$PATH"
export TIZ_OUTPUT_DIR="$OUTPUT_DIR"
export TIZ_YTDLP_JS_RUNTIMES="deno:$DENO_BIN"

# Place an exported Netscape-format cookie file at:
#   $COOKIE_FILE
# The downloader auto-detects it there, so no extra export is required.

# Uncomment this only if yt-dlp needs to fetch EJS scripts remotely:
# export TIZ_YTDLP_REMOTE_COMPONENTS="ejs:github"
EOF

    chmod +x "$ENV_FILE"
}

echo "=== Tiz-Cycling Downloader Setup ==="
echo ""

echo "Creating directories..."
mkdir -p "$INSTALL_DIR"
mkdir -p "$OUTPUT_DIR"

echo "Installing project files..."
cp tiz_cycling_downloader.py "$INSTALL_DIR/"
cp README.md "$INSTALL_DIR/"
cp AGENTS.md "$INSTALL_DIR/"
cp setup.sh "$INSTALL_DIR/"
cp setup.ps1 "$INSTALL_DIR/"

echo "Creating Python venv..."
python3 -m venv "$VENV_DIR"

echo "Installing Python dependencies..."
"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet "yt-dlp[default]" requests beautifulsoup4 lxml
echo "Installed: yt-dlp[default], requests, beautifulsoup4, lxml"

install_deno
write_env_file

if command -v ffmpeg >/dev/null 2>&1; then
    echo "Found ffmpeg: $(command -v ffmpeg)"
else
    echo "WARNING: ffmpeg not found in PATH. Some YouTube formats may be limited until ffmpeg is installed."
fi

CRON_CMD="0 6 * * * . $ENV_FILE && cd $INSTALL_DIR && $VENV_DIR/bin/python tiz_cycling_downloader.py --since 1 >> $HOME/tiz_downloader.log 2>&1"

if crontab -l 2>/dev/null | grep -q "tiz_cycling_downloader"; then
    echo "Updating existing cron job..."
    crontab -l 2>/dev/null | grep -v "tiz_cycling_downloader" | { cat; echo "$CRON_CMD"; } | crontab -
else
    echo "Adding daily cron job (6 AM)..."
    (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "  Install dir:    $INSTALL_DIR"
echo "  Output dir:     $OUTPUT_DIR"
echo "  Local Deno:     $DENO_BIN"
echo "  Env file:       $ENV_FILE"
echo "  Cookie path:    $COOKIE_FILE"
echo "  Log file:       ~/tiz_downloader.log"
echo ""
echo "Usage:"
echo "  Source env:     . $ENV_FILE"
echo "  Dry run:        cd $INSTALL_DIR && . ./tiz-env.sh && $VENV_DIR/bin/python tiz_cycling_downloader.py --dry-run --since 1"
echo "  Run now:        cd $INSTALL_DIR && . ./tiz-env.sh && $VENV_DIR/bin/python tiz_cycling_downloader.py --since 1"
echo "  Single URL:     cd $INSTALL_DIR && . ./tiz-env.sh && $VENV_DIR/bin/python tiz_cycling_downloader.py --url 'https://tiz-cycling.tv/video/...'"
echo "  Add cookies:    copy youtube-cookies.txt to $COOKIE_FILE"
echo "  Check cron:     crontab -l"
echo "  View log:       tail -f ~/tiz_downloader.log"
echo ""
echo "Override defaults with environment variables:"
echo "  TIZ_OUTPUT_DIR=~/plex/sports/Cycling bash setup.sh"
